version: '3'
services:
  flask_app:
    build: ./backend
    container_name: flask_app
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:nadira@db:5432/postgres
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - flask_app

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nadira
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
