version: '3.8'

services:
  web:
    build: ./backend
    container_name: flask_app
    restart: always
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: angular_app
    restart: always
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - web

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: psy_service_db
      POSTGRES_USER: psy_user
      POSTGRES_PASSWORD: psy_pass
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - web
      - frontend

volumes:
  db_data: